# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a532afd199d8f4b3c09d1d9b20bb80ec9c527f35ca2c5aae234fa021c8bf7e1ad5e1e812c09e57e4d38cf234ef3452a46618687ada21d18149fe9823bfb57192

test:
  secret_key_base: 462addd8a869d42dbe2a9c8aa73b2c5a622bcf3801c63976caa6e3918dc3a24f8b0dd7a77ce942e5243d39e6c9d248f3d3d8690c8b544391c31387ac73b77e0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
